project_id = "ycvvuepfsebqpwmamqgg"

[functions.chat-with-agent]
verify_jwt = false

[functions.widget-chat]
verify_jwt = false

[functions.scrape-website]
verify_jwt = false

[functions.twilio-sms-webhook]
verify_jwt = false

[functions.openai-realtime-token]
verify_jwt = false

[functions.voice-widget]
verify_jwt = false
