// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycvvuepfsebqpwmamqgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljdnZ1ZXBmc2VicXB3bWFtcWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMDE0MTUsImV4cCI6MjA3Mjc3NzQxNX0.x0fLf_ItCGW1Uns1uiGKGqac-j03LHFGpRDXMiNy4RQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});